export const PUBSUB_EVENTS = {
  SOMETHING_ON_AGENT_ACCOUNT : "SOMETHING_ON_AGENT_ACCOUNT",
  CHECKING : "CHECKING",
  SOMETHING_CHANGED_TOPIC : "SOMETHING_CHANGED_TOPIC",
  AGENT_LOCK : "AGENT_LOCK",
  GROUP_CHANGING : "GROUP_CHANGING",
  TASK_CHANGING : "TASK_CHANGING",
  DISPOSITION_UPDATE : "DISPOSITION_UPDATE",
  FINISHED_CALLFILE : "FINISHED_CALLFILE",
  SOMETHING_NEW_ON_CALLFILE : "SOMETHING_NEW_ON_CALLFILE",
  NEW_BUCKET_MESSAGE: "NEW_BUCKET_MESSAGE"
}
